language: python

python:
  - "3.6"

# Install requirements
install: "pip install numpy pytest==3.0.* mypy"

# Run the unit tests
script:
    - cd src
    - python -m pytest -v
    - python -m mypy --ignore-missing-imports Problem*.py
    - python -m mypy --ignore-missing-imports euler/*.py
