language: python

python:
  - "3.5"
  - "3.6"
  # Defaults for Ubuntu 16.04
  - "3.5.2"
  # Defaults for Ubuntu 18.04
  - "3.6.7"

matrix:
  include:
    - python: "3.7"
      dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)

# Install requirements
install: pip install numpy pytest mypy

# Run the unit tests
script:
    - cd src
    - python -m pytest -v
    - python -m mypy --ignore-missing-imports Problem*.py
    - python -m mypy --ignore-missing-imports euler/*.py
